# Generated by Django 5.2.4 on 2025-07-27 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parameterization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('identification', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('first_last_name', models.CharField(max_length=255)),
                ('second_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField()),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_date', models.DateField()),
                ('modification_date', models.DateField()),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_type', to='parameterization.types')),
                ('gender_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gender_type', to='parameterization.types')),
                ('id_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parameterization.city')),
                ('person_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parameterization.statues')),
            ],
            options={
                'db_table': 'persons',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('creation_date', models.DateField()),
                ('modification_date', models.DateField()),
                ('id_responsible_user', models.ForeignKey(db_column='id_responsible_user', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.user')),
                ('identification', models.ForeignKey(db_column='identification', on_delete=django.db.models.deletion.PROTECT, to='users.person')),
                ('user_status', models.ForeignKey(db_column='user_status', on_delete=django.db.models.deletion.PROTECT, to='parameterization.statues')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id_role', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('modification_date', models.DateTimeField()),
                ('creation_date', models.DateTimeField()),
                ('rol_status', models.ForeignKey(db_column='rol_status', on_delete=django.db.models.deletion.PROTECT, to='parameterization.statues')),
                ('id_responsible_user', models.ForeignKey(db_column='id_responsible_user', on_delete=django.db.models.deletion.PROTECT, to='users.user')),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='id_responsible_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.user'),
        ),
        migrations.CreateModel(
            name='UsersRoles',
            fields=[
                ('id_users_roles', models.IntegerField(primary_key=True, serialize=False)),
                ('id_role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.role')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.user')),
            ],
            options={
                'db_table': 'users_roles',
                'unique_together': {('id_user', 'id_role')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(related_name='users', through='users.UsersRoles', to='users.role'),
        ),
    ]
