# Generated by Django 5.2.4 on 2025-08-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
