# Generated by Django 5.2.4 on 2025-08-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_user',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
