# Generated by Django 5.2.4 on 2025-07-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='id_role',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersroles',
            name='id_users_roles',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
