# Generated by Django 5.2.4 on 2025-07-30 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_role_id_role_alter_usersroles_id_users_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identification',
            field=models.ForeignKey(db_column='identification', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.person'),
        ),
    ]
