# Generated by Django 5.2.4 on 2025-07-30 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_identification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='id_responsible_user',
            field=models.ForeignKey(db_column='id_responsible_user', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.user'),
        ),
    ]
