# Generated by Django 5.2.4 on 2025-10-08 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parameterization', '0013_remove_units_description_units_id_types_units_symbol_and_more'),
        ('users', '0002_alter_user_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id_document_type', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'document_type',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id_customer', models.AutoField(primary_key=True, serialize=False)),
                ('document_number', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('second_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('customer_statues', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_statues', to='parameterization.statues')),
                ('id_responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_for_customers', to='users.user')),
                ('id_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_profile', to='users.user')),
                ('person_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='person_type', to='parameterization.types')),
                ('type_document_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='service_requests.documenttype')),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
