# Generated by Django 5.2.4 on 2025-10-09 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonType',
            fields=[
                ('id_person_type', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'person_type',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='check_digit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='id_municipality',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='legal_entity_name',
            field=models.CharField(default='empresa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='tax_regime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='person_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_type', to='service_requests.persontype'),
        ),
    ]
