# Generated by Django 5.2.4 on 2025-10-09 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0002_persontype_customer_check_digit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tax_regime',
            field=models.IntegerField(),
        ),
    ]
