# Generated by Django 5.2.4 on 2025-10-10 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameterization', '0013_remove_units_description_units_id_types_units_symbol_and_more'),
        ('service_requests', '0003_alter_customer_tax_regime'),
        ('users', '0002_alter_user_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id_service', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('base_price', models.FloatField()),
                ('applicable_tax', models.IntegerField()),
                ('tax_rate', models.FloatField(blank=True, null=True)),
                ('is_vat_exempt', models.BooleanField(blank=True, default=False, null=True)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('id_responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_for_services', to='users.user')),
                ('price_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_price_unit', to='parameterization.units')),
                ('service_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_status', to='parameterization.statues')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_type', to='parameterization.types')),
            ],
            options={
                'db_table': 'services',
            },
        ),
    ]
