# Generated by Django 5.2.4 on 2025-10-11 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0004_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRegime',
            fields=[
                ('id_tax_regime', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tax_regime',
            },
        ),
        migrations.AlterField(
            model_name='customer',
            name='tax_regime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_regime', to='service_requests.taxregime'),
        ),
    ]
