# Generated by Django 5.2.4 on 2025-10-13 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameterization', '0013_remove_units_description_units_id_types_units_symbol_and_more'),
        ('service_requests', '0005_taxregime_alter_customer_tax_regime'),
        ('users', '0002_alter_user_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id_request', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('request_detail', models.TextField(max_length=600)),
                ('scheduled_start_date', models.DateField()),
                ('scheduled_end_date', models.DateField()),
                ('payment_method', models.IntegerField(blank=True, null=True)),
                ('amount_paid', models.FloatField(blank=True, null=True)),
                ('amount_to_pay', models.FloatField(blank=True, null=True)),
                ('confirmation_datetime', models.DateTimeField(blank=True, null=True)),
                ('completion_cancellation_observations', models.TextField(blank=True, max_length=500, null=True)),
                ('completion_cancellation_datetime', models.DateTimeField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('completion_cancellation_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_cancelled_requests', to='users.user')),
                ('confirmation_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_requests', to='users.user')),
                ('currency_unit_amount_paid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='currency_paid_requests', to='parameterization.units')),
                ('currency_unit_amount_to_pay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='currency_to_pay_requests', to='parameterization.units')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='service_requests.customer')),
                ('id_responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_user', to='users.user')),
                ('payment_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_status_requests', to='parameterization.statues')),
                ('request_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_requests', to='parameterization.statues')),
            ],
            options={
                'db_table': 'service_requests',
            },
        ),
        migrations.CreateModel(
            name='RequestLocation',
            fields=[
                ('id_request_location', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('city_id', models.IntegerField()),
                ('place_name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('area', models.FloatField()),
                ('humidity_level', models.FloatField()),
                ('altitude', models.FloatField()),
                ('altitude_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='altitude_locations', to='parameterization.units')),
                ('area_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='area_locations', to='parameterization.units')),
                ('soil_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='soil_type_locations', to='parameterization.types')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='request_location', to='service_requests.servicerequest')),
            ],
            options={
                'db_table': 'request_locations',
            },
        ),
    ]
