# Generated by Django 5.2.4 on 2025-10-13 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0016_merge_20251004_0033'),
        ('service_requests', '0006_servicerequest_requestlocation'),
        ('users', '0002_alter_user_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestMachineryUser',
            fields=[
                ('id_request_machinery_user', models.AutoField(primary_key=True, serialize=False)),
                ('machinery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_assignments', to='machinery.machinery')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machinery_users', to='service_requests.servicerequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_assignments', to='users.user')),
            ],
            options={
                'db_table': 'request_machinery_users',
                'unique_together': {('request', 'machinery', 'user')},
            },
        ),
    ]
