# Generated by Django 5.2.4 on 2025-10-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0007_requestmachineryuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bussiness_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
