# Generated by Django 5.2.4 on 2025-10-16 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0008_customer_bussiness_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'db_table': 'payment_methods',
            },
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_method_requests', to='service_requests.paymentmethod'),
        ),
    ]
