# Generated by Django 5.2.4 on 2025-10-16 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameterization', '0013_remove_units_description_units_id_types_units_symbol_and_more'),
        ('service_requests', '0009_paymentmethod_alter_servicerequest_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlocation',
            name='altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestlocation',
            name='altitude_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='altitude_locations', to='parameterization.units'),
        ),
        migrations.AlterField(
            model_name='requestlocation',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestlocation',
            name='area_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='area_locations', to='parameterization.units'),
        ),
        migrations.AlterField(
            model_name='requestlocation',
            name='humidity_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestlocation',
            name='soil_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='soil_type_locations', to='parameterization.types'),
        ),
    ]
