# Generated by Django 5.2.4 on 2025-10-18 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0016_merge_20251004_0033'),
        ('service_requests', '0010_alter_requestlocation_altitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Implementation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('real_name', models.CharField(max_length=50)),
                ('k_base', models.FloatField(blank=True, null=True)),
                ('n', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'implementations',
            },
        ),
        migrations.CreateModel(
            name='SoilType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('surface', models.CharField(max_length=50)),
                ('low', models.FloatField(blank=True, null=True)),
                ('medium', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('very_high', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'soil_types',
            },
        ),
        migrations.CreateModel(
            name='Texture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texture', models.CharField(max_length=50)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'textures',
            },
        ),
        migrations.AlterUniqueTogether(
            name='requestmachineryuser',
            unique_together={('request', 'machinery')},
        ),
        migrations.RemoveField(
            model_name='requestlocation',
            name='humidity_level',
        ),
        migrations.RemoveField(
            model_name='requestlocation',
            name='soil_type',
        ),
        migrations.AddField(
            model_name='requestmachineryuser',
            name='depth',
            field=models.FloatField(blank=True, null=True, verbose_name='depth'),
        ),
        migrations.AddField(
            model_name='requestmachineryuser',
            name='humidity_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestmachineryuser',
            name='slope',
            field=models.FloatField(blank=True, null=True, verbose_name='slope'),
        ),
        migrations.AddField(
            model_name='requestmachineryuser',
            name='work_duration',
            field=models.FloatField(blank=True, null=True, verbose_name='work_duration'),
        ),
        migrations.AddField(
            model_name='requestmachineryuser',
            name='implementation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machinery_implementation', to='service_requests.implementation'),
        ),
        migrations.AddField(
            model_name='requestmachineryuser',
            name='soil_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='soil_type', to='service_requests.soiltype'),
        ),
        migrations.AddField(
            model_name='requestmachineryuser',
            name='texture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machinery_texture_assignments', to='service_requests.texture'),
        ),
    ]
