# Generated by Django 5.2.4 on 2025-10-19 22:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0011_implementation_soiltype_texture_and_more'),
        ('users', '0002_alter_user_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id_invoice', models.AutoField(primary_key=True, serialize=False)),
                ('reference_code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada al API'), ('ACEPTADA', 'Aceptada por la DIAN'), ('RECHAZADA', 'Rechazada'), ('PAGADA', 'Pagada')], default='BORRADOR', max_length=50)),
                ('observation', models.TextField(blank=True, null=True)),
                ('total_without_taxes', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_taxes', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('amount_to_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('cufe', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('api_response', models.JSONField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.user')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='service_requests.customer')),
                ('service_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='service_requests.servicerequest')),
                ('tax_regime', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service_requests.taxregime')),
            ],
            options={
                'db_table': 'invoice',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id_invoice_line', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=255)),
                ('code_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_unit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('percentage_taxes_per_line', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('tax_per_line_type', models.CharField(default='IVA', max_length=50)),
                ('units_measurement_id', models.IntegerField(default=70)),
                ('tribute_id', models.CharField(default='1', max_length=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='service_requests.invoice')),
                ('service_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service_requests.service')),
            ],
            options={
                'db_table': 'invoice_line',
            },
        ),
    ]
