# Generated by Django 5.2.4 on 2025-10-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0012_invoice_invoiceline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada al API'), ('ACEPTADA', 'Aceptada por la DIAN'), ('RECHAZADA', 'Rechazada'), ('PAGADA', 'Pagada'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=50),
        ),
    ]
