# Generated by Django 5.2.4 on 2025-10-23 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0014_alter_invoice_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceIssuer',
            fields=[
                ('id_invoice_issuer', models.AutoField(primary_key=True, serialize=False)),
                ('issuer_name', models.CharField(max_length=255)),
                ('issuer_identification', models.CharField(blank=True, max_length=100, null=True)),
                ('issuer_address', models.CharField(blank=True, max_length=255, null=True)),
                ('issuer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('issuer_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='issuer', to='service_requests.invoice')),
            ],
            options={
                'db_table': 'invoice_issuer',
            },
        ),
    ]
