# Generated by Django 5.2.4 on 2025-10-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0015_invoiceissuer'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='firebase_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
