# Generated by Django 5.2.4 on 2025-10-24 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameterization', '0013_remove_units_description_units_id_types_units_symbol_and_more'),
        ('service_requests', '0016_invoice_firebase_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.ForeignKey(help_text='Estado actual de la factura (ref: Statues)', on_delete=django.db.models.deletion.PROTECT, to='parameterization.statues'),
        ),
    ]
