# Generated by Django 5.2.4 on 2025-10-24 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0017_alter_invoice_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='due_date',
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.ForeignKey(blank=True, help_text='Método de pago (ref: PaymentMethod)', null=True, on_delete=django.db.models.deletion.PROTECT, to='service_requests.paymentmethod'),
        ),
    ]
