# Generated by Django 5.2.4 on 2025-10-26 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0018_remove_invoice_created_by_remove_invoice_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceissuer',
            name='issuer_municipality',
            field=models.IntegerField(blank=True, help_text='ID del municipio del emisor', null=True),
        ),
    ]
