# Generated by Django 5.2.4 on 2025-10-26 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0019_invoiceissuer_issuer_municipality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceissuer',
            name='invoice',
            field=models.OneToOneField(blank=True, help_text='Configurado para ser null por modelo de negocio.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issuer', to='service_requests.invoice'),
        ),
    ]
