# Generated by Django 5.2.4 on 2025-10-26 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0020_alter_invoiceissuer_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_withholding_taxes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='withholding_taxes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
