# Generated by Django 5.2.4 on 2025-10-29 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0012_alter_service_id_service'),
        ('service_requests', '0023_alter_invoiceissuer_invoice'),
    ]

    operations = [
    ]
