# Generated by Django 5.2.4 on 2025-11-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0024_merge_20251029_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmachineryuser',
            name='implement_width',
            field=models.FloatField(blank=True, null=True, verbose_name='implement_width'),
        ),
    ]
