# Generated by Django 5.2.4 on 2025-11-13 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0025_requestmachineryuser_implement_width'),
    ]

    operations = [
    ]
