# Generated by Django 5.2.4 on 2026-04-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0026_auto_20251113_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='accounting_account',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
