services:
  cron:
    build: .
    container_name: django_cron
    command: bash -c "python manage.py crontab remove || true; python manage.py crontab add; cron -f"
    env_file:
      - .env
    environment:
      SERVICE_NAME: machpayroll
      AUDIT_URL: ${AUDIT_URL}
      AUDIT_TOKEN: ${AUDIT_TOKEN}
      AUDIT_HTTP_TIMEOUT: "1.5"
      X_CSCAPI_KEY: ${X_CSCAPI_KEY}
    networks:
      - shared_net

networks:
  app_network:
    driver: bridge
    name: app_network
