services:
  telemetry_processor:
    build: .
    container_name: telemetry_processor
    command: python manage.py process_telemetry
    env_file:
      - .env
    environment:
      SERVICE_NAME: machpayroll
      AUDIT_URL: ${AUDIT_URL}
      AUDIT_TOKEN: ${AUDIT_TOKEN}
      AUDIT_HTTP_TIMEOUT: "1.5"
      X_CSCAPI_KEY: ${X_CSCAPI_KEY}
      WEBSOCKET_PASSWORD: ${WEBSOCKET_PASSWORD}
    networks:
      - shared_net
    restart: always

networks:
  shared_net:
    external: true
