services:
  simulator:
    build: ./telemetry_simulator
    container_name: telemetry_simulator
    ports:
      - "8003:8000"
    environment:
      DEVICE_IMEI: ${DEVICE_IMEI:-357894561234567}
      ALLOW_GENERATE_IMEI: ${ALLOW_GENERATE_IMEI:-true}
      WEBSOCKET_PASSWORD: ${WEBSOCKET_PASSWORD}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --no-access-log
    networks:
      - shared_net
    restart: always

networks:
  shared_net:
    external: true
