# Generated by Django 5.2.4 on 2025-07-27 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id_country', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Statues',
            fields=[
                ('id_statues', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('modification_date', models.DateTimeField()),
                ('creation_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'statues',
            },
        ),
        migrations.CreateModel(
            name='StatuesCategory',
            fields=[
                ('id_statues_categories', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('modification_date', models.DateTimeField()),
                ('creation_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'statues_categories',
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id_types', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField()),
                ('modification_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'types',
            },
        ),
        migrations.CreateModel(
            name='TypesCategory',
            fields=[
                ('id_types_categories', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField()),
                ('modification_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'types_categories',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('id_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parameterization.country')),
            ],
            options={
                'db_table': 'regions',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id_city', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('id_region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parameterization.region')),
            ],
            options={
                'db_table': 'cities',
            },
        ),
    ]
