# Generated by Django 5.2.4 on 2025-08-24 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatuesCategory',
            fields=[
                ('id_statues_categories', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('modification_date', models.DateTimeField()),
                ('creation_date', models.DateTimeField()),
                ('id_responsible_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.user')),
            ],
            options={
                'db_table': 'statues_categories',
            },
        ),
        migrations.CreateModel(
            name='Statues',
            fields=[
                ('id_statues', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('modification_date', models.DateTimeField()),
                ('creation_date', models.DateTimeField()),
                ('id_responsible_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.user')),
                ('id_statues_categories', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parameterization.statuescategory')),
            ],
            options={
                'db_table': 'statues',
            },
        ),
        migrations.CreateModel(
            name='TypesCategory',
            fields=[
                ('id_types_categories', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField()),
                ('modification_date', models.DateTimeField()),
                ('id_responsible_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.user')),
            ],
            options={
                'db_table': 'types_categories',
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id_types', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField()),
                ('modification_date', models.DateTimeField()),
                ('id_responsible_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.user')),
                ('id_statues', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parameterization.statues')),
                ('id_types_categories', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parameterization.typescategory')),
            ],
            options={
                'db_table': 'types',
            },
        ),
    ]
