# Generated by Django 5.2.4 on 2025-09-03 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameterization', '0001_initial'),
        ('users', '0002_alter_user_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDepartment',
            fields=[
                ('id_employee_department', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('modification_date', models.DateTimeField(null=True)),
                ('creation_date', models.DateTimeField(null=True)),
                ('id_responsible_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.user')),
                ('id_statues', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='parameterization.statues')),
            ],
            options={
                'db_table': 'employee_departments',
            },
        ),
    ]
