# Generated by Django 5.2.4 on 2025-09-03 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameterization', '0001_initial'),
        ('users', '0002_alter_user_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualParameterization',
            fields=[
                ('id_visual_parameterization', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('background_color', models.CharField(blank=True, max_length=255, null=True)),
                ('text_color', models.CharField(blank=True, max_length=255, null=True)),
                ('font', models.CharField(blank=True, max_length=255, null=True)),
                ('font_size', models.CharField(blank=True, max_length=255, null=True)),
                ('border_thickness', models.CharField(blank=True, max_length=255, null=True)),
                ('border_color', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_date', models.DateTimeField(blank=True, null=True)),
                ('creation_date', models.DateTimeField()),
                ('id_responsible_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.user')),
                ('visual_parameterization_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parameterization.statues')),
            ],
            options={
                'db_table': 'visual_parameterization',
            },
        ),
    ]
