# Generated by Django 5.2.4 on 2025-09-03 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameterization', '0001_initial'),
        ('users', '0002_alter_user_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitsCategory',
            fields=[
                ('id_units_categories', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('modification_date', models.DateTimeField()),
                ('creation_date', models.DateTimeField()),
                ('id_responsible_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.user')),
            ],
            options={
                'db_table': 'units_categories',
            },
        ),
    ]
