# Generated by Django 5.2.4 on 2025-07-27 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parameterization', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statues',
            name='id_responsible_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.user'),
        ),
        migrations.AddField(
            model_name='statuescategory',
            name='id_responsible_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.user'),
        ),
        migrations.AddField(
            model_name='statues',
            name='id_statues_categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parameterization.statuescategory'),
        ),
        migrations.AddField(
            model_name='types',
            name='id_responsible_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.user'),
        ),
        migrations.AddField(
            model_name='types',
            name='id_statues',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parameterization.statues'),
        ),
        migrations.AddField(
            model_name='typescategory',
            name='id_responsible_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.user'),
        ),
        migrations.AddField(
            model_name='types',
            name='id_types_categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parameterization.typescategory'),
        ),
    ]
