# Generated by Django 5.2.4 on 2025-07-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameterization', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='id_city',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='country',
            name='id_country',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='region',
            name='id_region',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='statues',
            name='id_statues',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='statuescategory',
            name='id_statues_categories',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='types',
            name='id_types',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typescategory',
            name='id_types_categories',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
