# Generated by Django 5.2.4 on 2025-09-03 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameterization', '0002_visualparameterization'),
        ('users', '0002_alter_user_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVisualParameterization',
            fields=[
                ('id_user_visual_parameterization', models.AutoField(primary_key=True, serialize=False)),
                ('registration_date', models.DateTimeField()),
                ('modification_date', models.DateTimeField(blank=True, null=True)),
                ('id_responsible_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_user_visual_parameterizations', to='users.user')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_visual_parameterizations', to='users.user')),
                ('id_visual_parameterization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_assignments', to='parameterization.visualparameterization')),
                ('user_visual_parameterization_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_visual_parameterization_statuses', to='parameterization.statues')),
            ],
            options={
                'db_table': 'user_visual_parameterization',
            },
        ),
    ]
