# Generated by Django 5.2.4 on 2025-07-30 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameterization', '0003_alter_city_id_city_alter_country_id_country_and_more'),
        ('users', '0002_alter_role_id_role_alter_usersroles_id_users_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statues',
            name='id_responsible_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.user'),
        ),
        migrations.AlterField(
            model_name='statuescategory',
            name='id_responsible_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.user'),
        ),
        migrations.AlterField(
            model_name='types',
            name='id_statues',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='parameterization.statues'),
        ),
        migrations.AlterField(
            model_name='typescategory',
            name='id_responsible_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.user'),
        ),
    ]
