# Generated by Django 5.2.4 on 2025-09-03 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameterization', '0003_units'),
        ('parameterization', '0003_uservisualparameterization'),
    ]

    operations = [
    ]
