# Generated by Django 5.2.4 on 2025-09-05 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameterization', '0002_employeedepartment'),
        ('parameterization', '0004_merge_0003_units_0003_uservisualparameterization'),
    ]

    operations = [
    ]
