# Generated by Django 5.2.4 on 2025-09-06 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameterization', '0004_merge_0003_units_0003_uservisualparameterization'),
        ('users', '0002_alter_user_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandsCategory',
            fields=[
                ('id_brands_categories', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('modification_date', models.DateTimeField()),
                ('creation_date', models.DateTimeField()),
                ('id_responsible_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.user')),
            ],
            options={
                'db_table': 'brands_categories',
            },
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id_brands', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('modification_date', models.DateTimeField()),
                ('creation_date', models.DateTimeField()),
                ('id_responsible_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.user')),
                ('id_statues', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parameterization.statues')),
                ('id_brands_categories', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parameterization.brandscategory')),
            ],
            options={
                'db_table': 'brands',
            },
        ),
    ]
