# Generated by Django 5.2.4 on 2025-09-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameterization', '0005_brandscategory_brands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='statues',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='types',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
