# Generated by Django 5.2.4 on 2025-09-06 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameterization', '0005_brandscategory_brands'),
        ('users', '0002_alter_user_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id_model', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('modification_date', models.DateTimeField(null=True)),
                ('creation_date', models.DateTimeField(null=True)),
                ('id_brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='parameterization.brands')),
                ('id_responsible_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.user')),
            ],
            options={
                'db_table': 'models',
            },
        ),
    ]
