# Generated by Django 5.2.4 on 2025-09-08 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameterization', '0005_merge_20250905_1630'),
        ('parameterization', '0006_alter_brands_name_alter_statues_name_and_more'),
    ]

    operations = [
    ]
