# Generated by Django 5.2.4 on 2025-09-06 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameterization', '0006_models'),
        ('users', '0002_alter_user_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='models',
            name='id_statues',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='parameterization.statues'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='models',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='brands',
            constraint=models.UniqueConstraint(fields=('name', 'id_brands_categories'), name='uniq_brand_name_per_category'),
        ),
        migrations.AddConstraint(
            model_name='models',
            constraint=models.UniqueConstraint(fields=('name', 'id_brand'), name='uniq_model_name_per_brand'),
        ),
    ]
