# Generated by Django 5.2.4 on 2025-09-07 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameterization', '0006_alter_brands_name_alter_statues_name_and_more'),
        ('parameterization', '0007_models_id_statues_alter_brands_name_and_more'),
    ]

    operations = [
    ]
