# Generated by Django 5.2.4 on 2025-09-08 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameterization', '0007_merge_20250908_1518'),
        ('users', '0002_alter_user_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCharge',
            fields=[
                ('id_employee_charge', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('modification_date', models.DateTimeField(null=True)),
                ('creation_date', models.DateTimeField(null=True)),
                ('id_employee_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='parameterization.employeedepartment')),
                ('id_responsible_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.user')),
                ('id_statues', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parameterization.statues')),
            ],
            options={
                'db_table': 'employee_charges',
            },
        ),
    ]
