# Generated by Django 5.2.4 on 2025-09-08 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameterization', '0008_employeecharge'),
        ('parameterization', '0008_merge_20250907_0949'),
    ]

    operations = [
    ]
