# Generated by Django 5.2.4 on 2025-09-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameterization', '0008_merge_20250907_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualparameterization',
            name='accent_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visualparameterization',
            name='error_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visualparameterization',
            name='hover_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visualparameterization',
            name='paragraph_size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='visualparameterization',
            name='primary_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visualparameterization',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visualparameterization',
            name='success_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visualparameterization',
            name='surface_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visualparameterization',
            name='text_secondary_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visualparameterization',
            name='title_size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='visualparameterization',
            name='warning_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
