# Generated by Django 5.2.4 on 2025-09-08 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameterization', '0009_merge_0008_employeecharge_0008_merge_20250907_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedepartment',
            name='id_statues',
        ),
    ]
