# Generated by Django 5.2.4 on 2025-09-09 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameterization', '0009_visualparameterization_accent_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualparameterization',
            name='border_thickness',
        ),
        migrations.RemoveField(
            model_name='visualparameterization',
            name='font_size',
        ),
    ]
