# Generated by Django 5.2.4 on 2025-09-09 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameterization', '0010_remove_employeedepartment_id_statues'),
        ('parameterization', '0010_remove_visualparameterization_border_thickness_and_more'),
    ]

    operations = [
    ]
