# Generated by Django 5.2.4 on 2025-09-10 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameterization', '0011_merge_20250909_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedepartment',
            name='id_statues',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='parameterization.statues'),
            preserve_default=False,
        ),
    ]
