# Generated by Django 5.2.4 on 2025-09-10 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameterization', '0012_employeedepartment_id_statues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='units',
            name='description',
        ),
        migrations.AddField(
            model_name='units',
            name='id_types',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='parameterization.types'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='units',
            name='symbol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='units',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='units',
            name='id_units_categories',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='parameterization.unitscategory'),
        ),
        migrations.AlterField(
            model_name='units',
            name='modification_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
