# Generated by Django 5.2.4 on 2025-09-20 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameterization', '0011_merge_20250910_0152'),
        ('parameterization', '0013_remove_units_description_units_id_types_units_symbol_and_more'),
    ]

    operations = [
    ]
