# Generated by Django 5.2.4 on 2025-11-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameterization', '0013_remove_units_description_units_id_types_units_symbol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecharge',
            name='contract_prefix',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
