# Generated by Django 5.2.4 on 2026-04-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameterization', '0014_employeecharge_contract_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='types',
            name='accounting_account',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
