# Generated by Django 5.2.4 on 2025-11-22 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameterization', '0014_employeecharge_contract_prefix'),
        ('parameterization', '0014_merge_20250920_1733'),
    ]

    operations = [
    ]
