# Generated by Django 5.2.4 on 2026-04-20 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameterization', '0015_types_accounting_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='types',
            old_name='accounting_account',
            new_name='credit_account_code',
        ),
        migrations.AddField(
            model_name='types',
            name='debit_account_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
