# Generated by Django 5.2.4 on 2025-09-19 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parameterization', '0013_remove_units_description_units_id_types_units_symbol_and_more'),
        ('users', '0002_alter_user_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryDevices',
            fields=[
                ('id_device', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('registration_date', models.DateTimeField(auto_now=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('id_responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.user')),
                ('id_statues', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parameterization.statues')),
            ],
            options={
                'db_table': 'telemetry_devices',
            },
        ),
        migrations.CreateModel(
            name='Machinery',
            fields=[
                ('id_machinery', models.AutoField(primary_key=True, serialize=False)),
                ('machinery_name', models.CharField(max_length=255)),
                ('manufacturing_year', models.IntegerField(blank=True, null=True)),
                ('serial_number', models.CharField(max_length=50)),
                ('tariff_subheading', models.CharField(blank=True, max_length=50, null=True)),
                ('id_city', models.IntegerField(blank=True, null=True)),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_date', models.DateField(auto_now=True)),
                ('modification_date', models.DateField(auto_now=True)),
                ('id_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parameterization.models')),
                ('id_responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.user')),
                ('machinery_operational_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parameterization.statues')),
                ('machinery_secondary_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machinery_secondary_type', to='parameterization.types')),
                ('machinery_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machinery_type', to='parameterization.types')),
                ('id_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='machinery.telemetrydevices')),
            ],
            options={
                'db_table': 'machinery',
            },
        ),
    ]
