# Generated by Django 5.2.4 on 2025-09-22 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0001_initial'),
        ('users', '0002_alter_user_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineryTrackerSheet',
            fields=[
                ('id_tracker_sheet', models.AutoField(primary_key=True, serialize=False)),
                ('terminal_serial_number', models.CharField(max_length=100)),
                ('gps_serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('chassis_number', models.CharField(blank=True, max_length=100, null=True)),
                ('engine_number', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_date', models.DateField(auto_now=True)),
                ('modification_date', models.DateField(auto_now=True)),
                ('id_machinery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='machinery.machinery')),
                ('id_responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.user')),
            ],
            options={
                'db_table': 'machinery_tracker_sheet',
            },
        ),
    ]
