# Generated by Django 5.2.4 on 2025-09-22 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0001_initial'),
        ('parameterization', '0013_remove_units_description_units_id_types_units_symbol_and_more'),
        ('users', '0002_alter_user_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificTechnicalSheet',
            fields=[
                ('id_specific_technical_sheet', models.AutoField(primary_key=True, serialize=False)),
                ('power', models.FloatField()),
                ('cylinder_capacity', models.FloatField()),
                ('cylinder_count', models.IntegerField()),
                ('fuel_consumption', models.FloatField()),
                ('fuel_capacity', models.FloatField(blank=True, null=True)),
                ('carrying_capacity', models.FloatField(blank=True, null=True)),
                ('operating_weight', models.CharField(max_length=255)),
                ('max_speed', models.FloatField()),
                ('draft_force', models.FloatField(blank=True, null=True)),
                ('maximum_altitude', models.FloatField(blank=True, null=True)),
                ('minimum_performance', models.IntegerField(blank=True, null=True)),
                ('maximum_performance', models.IntegerField(blank=True, null=True)),
                ('width', models.FloatField()),
                ('length', models.FloatField()),
                ('height', models.FloatField()),
                ('net_weight', models.FloatField()),
                ('air_conditioning_system_consumption', models.FloatField(blank=True, null=True)),
                ('maximum_working_pressure', models.FloatField(blank=True, null=True)),
                ('pump_flow', models.FloatField(blank=True, null=True)),
                ('hydraulic_tank_capacity', models.FloatField(blank=True, null=True)),
                ('registration_date', models.DateField(auto_now=True)),
                ('modification_date', models.DateField(auto_now=True)),
                ('air_conditioning_system_consumption_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='air_conditioning_system_consumption_unit', to='parameterization.units')),
                ('air_conditioning_system_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='air_conditioning_system_type', to='parameterization.types')),
                ('cabin_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cabin_type', to='parameterization.types')),
                ('carrying_capacity_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carrying_capacity_unit', to='parameterization.units')),
                ('cylinder_arrangement_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cylinder_arrangement_type', to='parameterization.types')),
                ('cylinder_capacity_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cylinder_capacity_unit', to='parameterization.units')),
                ('dimension_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dimension_unit', to='parameterization.units')),
                ('draft_force_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='draft_force_unit', to='parameterization.units')),
                ('emission_level_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emission_level_type', to='parameterization.types')),
                ('engine_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engine_type', to='parameterization.types')),
                ('fuel_capacity_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fuel_capacity_unit', to='parameterization.units')),
                ('fuel_consumption_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_consumption_unit', to='parameterization.units')),
                ('hydraulic_tank_capacity_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hydraulic_tank_capacity_unit', to='parameterization.units')),
                ('id_machinery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='machinery.machinery')),
                ('id_responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.user')),
                ('max_speed_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='max_speed_unit', to='parameterization.units')),
                ('maximum_altitude_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maximum_altitude_unit', to='parameterization.units')),
                ('maximum_working_pressure_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maximum_working_pressure_unit', to='parameterization.units')),
                ('net_weight_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='net_weight_unit', to='parameterization.units')),
                ('operating_weight_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operating_weight_unit', to='parameterization.units')),
                ('performance_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='performance_unit', to='parameterization.units')),
                ('power_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='power_unit', to='parameterization.units')),
                ('pump_flow_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pump_flow_unit', to='parameterization.units')),
                ('traction_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traction_type', to='parameterization.types')),
                ('transmission_system_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transmission_system_type', to='parameterization.types')),
            ],
            options={
                'db_table': 'specific_technical_sheets',
            },
        ),
    ]
