# Generated by Django 5.2.4 on 2025-09-22 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0001_initial'),
        ('users', '0002_alter_user_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineryDocumentation',
            fields=[
                ('id_machinery_documentation', models.AutoField(primary_key=True, serialize=False)),
                ('document', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=500)),
                ('creation_date', models.DateField()),
                ('id_machinery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.machinery')),
                ('id_responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.user')),
            ],
            options={
                'db_table': 'machinery_documentation',
                'constraints': [models.UniqueConstraint(fields=('document', 'id_machinery'), name='uniq_document_name_per_machinery')],
            },
        ),
    ]
