# Generated by Django 5.2.4 on 2025-09-22 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0002_machinerytrackersheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicMaintenanceScheduling',
            fields=[
                ('id_periodic_maintenance_scheduling', models.AutoField(db_column='id_periodic_maintenance_scheduling', primary_key=True, serialize=False)),
                ('usage_hours', models.PositiveIntegerField(blank=True, db_column='usage_hours', null=True)),
                ('distance_km', models.PositiveIntegerField(blank=True, db_column='distance_km', null=True)),
                ('machinery', models.ForeignKey(db_column='id_machinery', on_delete=django.db.models.deletion.CASCADE, related_name='periodic_maintenances', to='machinery.machinery')),
            ],
            options={
                'db_table': 'periodic_maintenance_scheduling',
            },
        ),
    ]
