# Generated by Django 5.2.4 on 2025-09-22 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0002_machinerytrackersheet'),
        ('parameterization', '0013_remove_units_description_units_id_types_units_symbol_and_more'),
        ('users', '0002_alter_user_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineryUsageSheet',
            fields=[
                ('id_usage_sheet', models.AutoField(primary_key=True, serialize=False)),
                ('acquisition_date', models.DateField()),
                ('usage_hours', models.DecimalField(decimal_places=2, max_digits=12)),
                ('distance_value', models.DecimalField(decimal_places=3, max_digits=14)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('registration_date', models.DateField(auto_now=True)),
                ('modification_date', models.DateField(auto_now=True)),
                ('distance_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parameterization.units')),
                ('id_machinery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='machinery.machinery')),
                ('id_responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.user')),
                ('tenancy_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenancy_type_machinery_usage_sheets', to='parameterization.types')),
                ('usage_condition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_condition_machinery_usage_sheets', to='parameterization.types')),
            ],
            options={
                'db_table': 'machinery_usage_sheet',
                'constraints': [models.UniqueConstraint(fields=('id_machinery',), name='unique_usage_sheet_per_machinery')],
            },
        ),
    ]
