# Generated by Django 5.2.4 on 2025-09-22 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0002_specifictechnicalsheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specifictechnicalsheet',
            name='id_machinery',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='machinery.machinery'),
        ),
    ]
