# Generated by Django 5.2.4 on 2025-09-22 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0003_periodicmaintenancescheduling'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodicmaintenancescheduling',
            name='maintenance',
            field=models.ForeignKey(db_column='id_maintenance', on_delete=django.db.models.deletion.PROTECT, related_name='periodic_schedules', to='maintenance.maintenance'),
        ),
        migrations.AddConstraint(
            model_name='periodicmaintenancescheduling',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('usage_hours__isnull', False), ('distance_km__isnull', True)), models.Q(('usage_hours__isnull', True), ('distance_km__isnull', False)), _connector='OR'), name='pm_exactly_one_trigger'),
        ),
        migrations.AddConstraint(
            model_name='periodicmaintenancescheduling',
            constraint=models.UniqueConstraint(condition=models.Q(('usage_hours__isnull', False)), fields=('machinery', 'maintenance', 'usage_hours'), name='uniq_pm_by_mach_maint_hours'),
        ),
        migrations.AddConstraint(
            model_name='periodicmaintenancescheduling',
            constraint=models.UniqueConstraint(condition=models.Q(('distance_km__isnull', False)), fields=('machinery', 'maintenance', 'distance_km'), name='uniq_pm_by_mach_maint_distance'),
        ),
    ]
