# Generated by Django 5.2.4 on 2025-09-22 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0003_machineryusagesheet'),
        ('parameterization', '0013_remove_units_description_units_id_types_units_symbol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineryusagesheet',
            name='tenancy_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenancy_type_machinery_usage_sheets', to='parameterization.types'),
        ),
    ]
