# Generated by Django 5.2.4 on 2025-09-23 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0004_alter_machineryusagesheet_tenancy_type'),
        ('parameterization', '0013_remove_units_description_units_id_types_units_symbol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineryusagesheet',
            name='is_own',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='machineryusagesheet',
            name='usage_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_condition_machinery_usage_sheets', to='parameterization.statues'),
        ),
    ]
