# Generated by Django 5.2.4 on 2025-09-23 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0004_periodicmaintenancescheduling_maintenance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodicmaintenancescheduling',
            name='machinery',
            field=models.ForeignKey(db_column='id_machinery', on_delete=django.db.models.deletion.PROTECT, related_name='periodic_maintenances', to='machinery.machinery'),
        ),
    ]
