# Generated by Django 5.2.4 on 2025-09-23 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0002_machinerydocumentation'),
        ('machinery', '0003_alter_specifictechnicalsheet_id_machinery'),
        ('machinery', '0005_alter_periodicmaintenancescheduling_machinery'),
        ('machinery', '0005_machineryusagesheet_is_own_and_more'),
    ]

    operations = [
    ]
