# Generated by Django 5.2.4 on 2025-09-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0006_merge_20250923_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinery',
            name='justification',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
