# Generated by Django 5.2.4 on 2025-09-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0007_machinery_justification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specifictechnicalsheet',
            name='operating_weight',
            field=models.FloatField(max_length=255),
        ),
    ]
