# Generated by Django 5.2.4 on 2025-09-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0008_alter_specifictechnicalsheet_operating_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinerydocumentation',
            name='justification',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='machinerytrackersheet',
            name='justification',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='machineryusagesheet',
            name='justification',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='specifictechnicalsheet',
            name='justification',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='telemetrydevices',
            name='justification',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
