# Generated by Django 5.2.4 on 2025-09-26 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0009_machinerydocumentation_justification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telemetrydevices',
            name='justification',
        ),
    ]
