# Generated by Django 5.2.4 on 2025-09-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0010_remove_telemetrydevices_justification'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinery',
            name='id_country',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinery',
            name='id_department',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
