# Generated by Django 5.2.4 on 2025-09-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0011_machinery_id_country_machinery_id_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinery',
            name='id_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='machinery',
            name='id_department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
