# Generated by Django 5.2.4 on 2025-09-30 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0011_machinery_id_country_machinery_id_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodicmaintenancescheduling',
            old_name='machinery',
            new_name='id_machinery',
        ),
        migrations.RenameField(
            model_name='periodicmaintenancescheduling',
            old_name='maintenance',
            new_name='id_maintenance',
        ),
    ]
