# Generated by Django 5.2.4 on 2025-09-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0012_rename_machinery_periodicmaintenancescheduling_id_machinery_and_more'),
        ('maintenance', '0009_maintenancerequest_justification_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='periodicmaintenancescheduling',
            name='uniq_pm_by_mach_maint_hours',
        ),
        migrations.RemoveConstraint(
            model_name='periodicmaintenancescheduling',
            name='uniq_pm_by_mach_maint_distance',
        ),
        migrations.AddConstraint(
            model_name='periodicmaintenancescheduling',
            constraint=models.UniqueConstraint(condition=models.Q(('usage_hours__isnull', False)), fields=('id_machinery', 'id_maintenance', 'usage_hours'), name='uniq_pm_by_mach_maint_hours'),
        ),
        migrations.AddConstraint(
            model_name='periodicmaintenancescheduling',
            constraint=models.UniqueConstraint(condition=models.Q(('distance_km__isnull', False)), fields=('id_machinery', 'id_maintenance', 'distance_km'), name='uniq_pm_by_mach_maint_distance'),
        ),
    ]
