# Generated by Django 5.2.4 on 2025-09-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0013_remove_periodicmaintenancescheduling_uniq_pm_by_mach_maint_hours_and_more'),
        ('maintenance', '0009_maintenancerequest_justification_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='periodicmaintenancescheduling',
            name='uniq_pm_by_mach_maint_hours',
        ),
        migrations.RemoveConstraint(
            model_name='periodicmaintenancescheduling',
            name='uniq_pm_by_mach_maint_distance',
        ),
        migrations.RenameField(
            model_name='periodicmaintenancescheduling',
            old_name='id_machinery',
            new_name='machinery',
        ),
        migrations.RenameField(
            model_name='periodicmaintenancescheduling',
            old_name='id_maintenance',
            new_name='maintenance',
        ),
        migrations.AddConstraint(
            model_name='periodicmaintenancescheduling',
            constraint=models.UniqueConstraint(condition=models.Q(('usage_hours__isnull', False)), fields=('machinery', 'maintenance', 'usage_hours'), name='uniq_pm_by_mach_maint_hours'),
        ),
        migrations.AddConstraint(
            model_name='periodicmaintenancescheduling',
            constraint=models.UniqueConstraint(condition=models.Q(('distance_km__isnull', False)), fields=('machinery', 'maintenance', 'distance_km'), name='uniq_pm_by_mach_maint_distance'),
        ),
    ]
