# Generated by Django 5.2.4 on 2025-10-02 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0012_alter_machinery_id_country_and_more'),
        ('machinery', '0014_remove_periodicmaintenancescheduling_uniq_pm_by_mach_maint_hours_and_more'),
    ]

    operations = [
    ]
