# Generated by Django 5.2.4 on 2025-10-04 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0015_merge_20251002_0031'),
        ('machinery', '0015_merge_20251002_0416'),
    ]

    operations = [
    ]
