# Generated by Django 5.2.4 on 2025-10-20 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0016_merge_20251004_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parameter_name', models.CharField(max_length=50)),
                ('avl_id_parameter', models.IntegerField(unique=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('minimum_range', models.BigIntegerField(blank=True, null=True)),
                ('maximum_range', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'parameters',
            },
        ),
        migrations.AddField(
            model_name='telemetrydevices',
            name='IMEI',
            field=models.BigIntegerField(default=1234),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TelemetryDeviceParameter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='machinery.parameters')),
                ('telemetry_device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='machinery.telemetrydevices')),
            ],
            options={
                'db_table': 'telemetry_device_parameter',
                'unique_together': {('telemetry_device', 'parameter')},
            },
        ),
    ]
