# Generated by Django 5.2.4 on 2025-10-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0017_parameters_telemetrydevices_imei_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
