# Generated by Django 5.2.4 on 2025-10-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0018_parameters_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='maximum_message',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parameters',
            name='minimun_message',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
