# Generated by Django 5.2.4 on 2025-10-24 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0019_parameters_maximum_message_and_more'),
        ('maintenance', '0020_remove_maintenancereport_creation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTypes',
            fields=[
                ('id_event_type', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'event_types',
            },
        ),
        migrations.CreateModel(
            name='OBD_Faults',
            fields=[
                ('id_obd_fault', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'obd_faults',
            },
        ),
        migrations.AddField(
            model_name='parameters',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='EventTypeMachinery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('alert_enabled', models.BooleanField(blank=True, null=True)),
                ('id_machinery', models.ForeignKey(db_column='id_machinery', on_delete=django.db.models.deletion.PROTECT, to='machinery.machinery')),
                ('id_maintenance', models.ForeignKey(blank=True, db_column='id_maintenance', null=True, on_delete=django.db.models.deletion.PROTECT, to='maintenance.maintenance')),
                ('id_event_type', models.ForeignKey(db_column='id_event_type', on_delete=django.db.models.deletion.PROTECT, to='machinery.eventtypes')),
            ],
            options={
                'db_table': 'event_type_machinery',
            },
        ),
        migrations.CreateModel(
            name='OBDFaultMachinery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_enabled', models.BooleanField(blank=True, null=True)),
                ('id_machinery', models.ForeignKey(db_column='id_machinery', on_delete=django.db.models.deletion.PROTECT, to='machinery.machinery')),
                ('id_maintenance', models.ForeignKey(blank=True, db_column='id_maintenance', null=True, on_delete=django.db.models.deletion.PROTECT, to='maintenance.maintenance')),
                ('id_obd_fault', models.ForeignKey(db_column='id_obd_fault', on_delete=django.db.models.deletion.PROTECT, to='machinery.obd_faults')),
            ],
            options={
                'db_table': 'obd_fault_machinery',
            },
        ),
        migrations.CreateModel(
            name='ToleranceThresholds',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('minimum_threshold', models.FloatField(blank=True, null=True)),
                ('maximum_threshold', models.FloatField(blank=True, null=True)),
                ('alert_enabled', models.BooleanField(blank=True, null=True)),
                ('id_machinery', models.ForeignKey(db_column='id_machinery', on_delete=django.db.models.deletion.PROTECT, to='machinery.machinery')),
                ('id_maintenance', models.ForeignKey(blank=True, db_column='id_maintenance', null=True, on_delete=django.db.models.deletion.PROTECT, to='maintenance.maintenance')),
                ('id_parameter', models.ForeignKey(db_column='id_parameter', on_delete=django.db.models.deletion.PROTECT, to='machinery.parameters')),
            ],
            options={
                'db_table': 'tolerance_thresholds',
            },
        ),
    ]
