# Generated by Django 5.2.4 on 2025-10-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0020_eventtypes_obd_faults_parameters_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtypemachinery',
            name='alert_enabled',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='obdfaultmachinery',
            name='alert_enabled',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tolerancethresholds',
            name='alert_enabled',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
