# Generated by Django 5.2.4 on 2025-11-12 22:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishedcontract',
            name='start_cumulative_vacation',
            field=models.DateField(blank=True, db_column='start_cumulative_vacation', null=True),
        ),
        migrations.RemoveField(
            model_name='contractpaymentsestablishedcontract',
            name='date_payment',
        ),
        migrations.AddField(
            model_name='contractpaymentsestablishedcontract',
            name='date_payment',
            field=models.IntegerField(db_column='date_payment', default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='establishedcontract',
            name='cumulative_vacation',
            field=models.BooleanField(blank=True, db_column='cumulative_vacation', null=True),
        ),
        migrations.AlterField(
            model_name='establishedcontract',
            name='overtime_period',
            field=models.CharField(blank=True, choices=[('dia', 'Día'), ('semana', 'Semana'), ('mes', 'Mes')], db_column='overtime_period', max_length=20, null=True),
        ),
    ]
