# Generated by Django 5.2.4 on 2025-11-15 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameterization', '0013_remove_units_description_units_id_types_units_symbol_and_more'),
        ('payroll', '0002_establishedcontract_start_cumulative_vacation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishedcontract',
            name='currency_type',
            field=models.ForeignKey(db_column='currency_type', on_delete=django.db.models.deletion.PROTECT, related_name='established_contracts_by_currency_type', to='parameterization.units'),
        ),
    ]
