# Generated by Django 5.2.4 on 2025-11-16 02:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_alter_establishedcontract_currency_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractpaymentsestablishedcontract',
            name='date_payment',
            field=models.IntegerField(blank=True, db_column='date_payment', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='contractpaymentsestablishedcontract',
            name='id_day_of_week',
            field=models.ForeignKey(blank=True, db_column='id_day_of_week', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_payments_by_day', to='payroll.daysofweek'),
        ),
        migrations.AlterField(
            model_name='establishedcontract',
            name='cumulative_vacation',
            field=models.BooleanField(db_column='cumulative_vacation', default=False),
            preserve_default=False,
        ),
    ]
