# Generated by Django 5.2.4 on 2025-11-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_alter_contractpaymentsestablishedcontract_date_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishedcontract',
            name='contract_code',
            field=models.CharField(db_column='contract_code', max_length=200, primary_key=True, serialize=False),
        ),
    ]
