# Generated by Django 5.2.4 on 2025-11-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_alter_establishedcontract_contract_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establisheddeduction',
            name='amount',
            field=models.FloatField(blank=True, db_column='amount', null=True),
        ),
        migrations.AlterField(
            model_name='establishedincrease',
            name='amount',
            field=models.FloatField(blank=True, db_column='amount', null=True),
        ),
    ]
