# Generated by Django 5.2.4 on 2025-11-19 06:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameterization', '0013_remove_units_description_units_id_types_units_symbol_and_more'),
        ('payroll', '0006_alter_establisheddeduction_amount_and_more'),
        ('users', '0002_alter_user_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id_employee', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(db_column='creation_date')),
                ('modification_date', models.DateTimeField(db_column='modification_date')),
                ('employee_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parameterization.statues')),
                ('id_employee_charge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parameterization.employeecharge')),
                ('id_responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_responsible_user', to='users.user')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.user')),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='EmployeeContract',
            fields=[
                ('contract_code', models.CharField(db_column='contract_code', max_length=200, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_column='description', max_length=100, null=True)),
                ('start_date', models.DateField(db_column='start_date')),
                ('end_date', models.DateField(db_column='end_date')),
                ('payment_frequency_type', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual')], db_column='payment_frequency_type', max_length=20)),
                ('minimum_hours', models.IntegerField(blank=True, db_column='minimum_hours', null=True)),
                ('salary_type', models.CharField(choices=[('Por horas', 'Por horas'), ('Por días', 'Por días'), ('Mensual fijo', 'Mensual fijo')], db_column='salary_type', max_length=20)),
                ('salary_base', models.FloatField(db_column='salary_base')),
                ('trial_period_days', models.IntegerField(blank=True, db_column='trial_period_days', null=True)),
                ('vacation_days', models.IntegerField(db_column='vacation_days')),
                ('cumulative_vacation', models.BooleanField(db_column='cumulative_vacation')),
                ('start_cumulative_vacation', models.DateField(blank=True, db_column='start_cumulative_vacation', null=True)),
                ('vacation_frequency_days', models.IntegerField(blank=True, db_column='vacation_frequency_days', null=True)),
                ('maximum_disability_days', models.IntegerField(db_column='maximum_disability_days')),
                ('overtime', models.FloatField(db_column='overtime')),
                ('overtime_period', models.CharField(blank=True, choices=[('dia', 'Día'), ('semana', 'Semana'), ('mes', 'Mes')], db_column='overtime_period', max_length=20, null=True)),
                ('notice_period_days', models.IntegerField(blank=True, db_column='notice_period_days', null=True)),
                ('secundary_petition', models.BooleanField(db_column='secundary_petition')),
                ('creation_date', models.DateTimeField(db_column='creation_date')),
                ('contract_status', models.ForeignKey(db_column='contract_status', on_delete=django.db.models.deletion.PROTECT, related_name='employee_contracts_by_status', to='parameterization.statues')),
                ('contract_type', models.ForeignKey(db_column='contract_type', on_delete=django.db.models.deletion.PROTECT, related_name='employee_contracts_by_contract_type', to='parameterization.types')),
                ('currency_type', models.ForeignKey(db_column='currency_type', on_delete=django.db.models.deletion.PROTECT, related_name='employee_contracts_by_currency_type', to='parameterization.units')),
                ('id_employee', models.ForeignKey(db_column='employees_id_employee', on_delete=django.db.models.deletion.PROTECT, related_name='employee_contracts', to='payroll.employee')),
                ('id_employee_charge', models.ForeignKey(db_column='employee_charges_id_employee_charge', on_delete=django.db.models.deletion.PROTECT, related_name='employee_contracts', to='parameterization.employeecharge')),
                ('id_employee_department', models.ForeignKey(db_column='employee_departments_id_employee_department', on_delete=django.db.models.deletion.PROTECT, related_name='employee_contracts', to='parameterization.employeedepartment')),
                ('id_responsible_user', models.ForeignKey(db_column='id_responsible_user', on_delete=django.db.models.deletion.PROTECT, related_name='employee_contracts_responsible', to='users.user')),
                ('work_mode_type', models.ForeignKey(blank=True, db_column='work_mode_type', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_contracts_by_work_mode_type', to='parameterization.types')),
                ('workday_type', models.ForeignKey(blank=True, db_column='workday_type', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_contracts_by_workday_type', to='parameterization.types')),
            ],
            options={
                'db_table': 'employee_contracts',
            },
        ),
        migrations.CreateModel(
            name='EmployeeContractDeduction',
            fields=[
                ('id_employee_contract_deduction', models.AutoField(db_column='id_employee_contract_deduction', primary_key=True, serialize=False)),
                ('amount_type', models.CharField(choices=[('Porcentaje', 'Porcentaje'), ('fijo', 'Fijo')], db_column='amount_type', max_length=20)),
                ('amount_value', models.FloatField(db_column='amount_value')),
                ('application_deduction_type', models.CharField(choices=[('SalarioBase', 'Salario Base'), ('SalarioFinal', 'Salario Final')], db_column='application_deduction_type', max_length=20)),
                ('start_date_deduction', models.DateField(blank=True, db_column='start_date_deduction', null=True)),
                ('end_date_deductions', models.DateField(blank=True, db_column='end_date_deductions', null=True)),
                ('description', models.CharField(blank=True, db_column='description', max_length=255, null=True)),
                ('amount', models.FloatField(blank=True, db_column='amount', null=True)),
                ('deduction_type', models.ForeignKey(db_column='deduction_type', on_delete=django.db.models.deletion.PROTECT, related_name='employee_contract_deductions_by_type', to='parameterization.types')),
                ('employee_contracts_contract_code', models.ForeignKey(blank=True, db_column='employee_contracts_contract_code', on_delete=django.db.models.deletion.PROTECT, related_name='employee_contract_deductions', to='payroll.employeecontract')),
            ],
            options={
                'db_table': 'employee_contract_deductions',
            },
        ),
        migrations.CreateModel(
            name='EmployeeContractIncrease',
            fields=[
                ('id_employee_contract_increase', models.AutoField(db_column='id_employee_contract_increase', primary_key=True, serialize=False)),
                ('amount_type', models.CharField(choices=[('Porcentaje', 'Porcentaje'), ('fijo', 'Fijo')], db_column='amount_type', max_length=20)),
                ('amount_value', models.FloatField(db_column='amount_value')),
                ('application_increase_type', models.CharField(choices=[('SalarioBase', 'Salario Base'), ('SalarioFinal', 'Salario Final')], db_column='application_increase_type', max_length=20)),
                ('start_date_increase', models.DateField(blank=True, db_column='start_date_increase', null=True)),
                ('end_date_increase', models.DateField(blank=True, db_column='end_date_increase', null=True)),
                ('description', models.CharField(blank=True, db_column='description', max_length=255, null=True)),
                ('amount', models.FloatField(blank=True, db_column='amount', null=True)),
                ('employee_contracts_contract_code', models.ForeignKey(db_column='employee_contracts_contract_code', on_delete=django.db.models.deletion.PROTECT, related_name='employee_contract_increases', to='payroll.employeecontract')),
                ('increase_type', models.ForeignKey(db_column='increase_type', on_delete=django.db.models.deletion.PROTECT, related_name='employee_contract_increases_by_type', to='parameterization.types')),
            ],
            options={
                'db_table': 'employee_contract_increases',
            },
        ),
        migrations.CreateModel(
            name='EmployeeContractPayment',
            fields=[
                ('id_contract_payment', models.AutoField(db_column='id_contract_payment', primary_key=True, serialize=False)),
                ('date_payment', models.IntegerField(blank=True, db_column='date_payment', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('employee_contracts_contract_code', models.ForeignKey(db_column='employee_contracts_contract_code', on_delete=django.db.models.deletion.PROTECT, related_name='contract_payments', to='payroll.employeecontract')),
                ('id_day_of_week', models.ForeignKey(blank=True, db_column='id_day_of_week', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_contract_payments_by_day', to='payroll.daysofweek')),
            ],
            options={
                'db_table': 'employee_contract_payments',
            },
        ),
    ]
