# Generated by Django 5.2.4 on 2025-11-19 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_employee_employeecontract_employeecontractdeduction_and_more'),
        ('users', '0002_alter_user_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.user', unique=True),
        ),
    ]
