# Generated by Django 5.2.4 on 2025-11-19 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_alter_employee_id_user'),
        ('users', '0002_alter_user_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='null', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EmployeeNews',
            fields=[
                ('id_employee_new', models.AutoField(primary_key=True, serialize=False)),
                ('observation', models.CharField(blank=True, max_length=255, null=True)),
                ('news_date', models.DateTimeField(auto_now_add=True)),
                ('news_type', models.CharField(choices=[('CREACION_EMPLEADO', 'Creación de empleado'), ('ACTUALIZACION_EMPLEADO', 'Actualizar empleado'), ('DESACTIVACION_EMPLEADO', 'Desactivar empleado'), ('GENERAR_OTRO_SI', 'Generar otro si'), ('CAMBIO_CONTRATO', 'Cambio de contrato'), ('FINALIZACION_CONTRATO', 'Finalización de contrato')], max_length=30)),
                ('id_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.employee')),
                ('id_responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.user')),
            ],
            options={
                'db_table': 'employee_news',
            },
        ),
    ]
