# Generated by Django 5.2.4 on 2025-11-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_employee_email_employeenews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecontract',
            name='end_date',
            field=models.DateField(blank=True, db_column='end_date', null=True),
        ),
        migrations.AlterField(
            model_name='establishedcontract',
            name='end_date',
            field=models.DateField(blank=True, db_column='end_date', null=True),
        ),
    ]
