# Generated by Django 5.2.4 on 2025-11-19 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_alter_employeecontract_end_date_and_more'),
        ('users', '0002_alter_user_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id_user',
            field=models.OneToOneField(blank=True, db_column='id_user', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.user'),
        ),
    ]
