# Generated by Django 5.2.4 on 2025-11-20 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameterization', '0013_remove_units_description_units_id_types_units_symbol_and_more'),
        ('payroll', '0011_alter_employee_id_user'),
        ('users', '0002_alter_user_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecontractdeduction',
            name='application_deduction_type',
            field=models.CharField(choices=[('SalarioBase', 'Salario Base'), ('SalarioFinal', 'Salario Final'), ('SalarioPorHora', 'Salario Por Hora')], db_column='application_deduction_type', max_length=20),
        ),
        migrations.AlterField(
            model_name='employeecontractincrease',
            name='application_increase_type',
            field=models.CharField(choices=[('SalarioBase', 'Salario Base'), ('SalarioFinal', 'Salario Final'), ('SalarioPorHora', 'Salario Por Hora')], db_column='application_increase_type', max_length=20),
        ),
        migrations.AlterField(
            model_name='establisheddeduction',
            name='application_deduction_type',
            field=models.CharField(choices=[('SalarioBase', 'Salario Base'), ('SalarioFinal', 'Salario Final'), ('SalarioPorHora', 'Salario Por Hora')], db_column='application_deduction_type', max_length=20),
        ),
        migrations.AlterField(
            model_name='establishedincrease',
            name='application_increase_type',
            field=models.CharField(choices=[('SalarioBase', 'Salario Base'), ('SalarioFinal', 'Salario Final'), ('SalarioPorHora', 'Salario Por Hora')], db_column='application_increase_type', max_length=20),
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id_payroll', models.AutoField(db_column='id_payroll', primary_key=True, serialize=False)),
                ('start_date', models.DateField(db_column='start_date')),
                ('end_date', models.DateField(db_column='end_date')),
                ('creation_date', models.DateTimeField(db_column='creation_date')),
                ('id_employee', models.ForeignKey(db_column='id_employee', on_delete=django.db.models.deletion.PROTECT, related_name='payrolls', to='payroll.employee')),
                ('id_employee_contract', models.ForeignKey(db_column='id_employee_contract', on_delete=django.db.models.deletion.PROTECT, related_name='payrolls_by_contract', to='payroll.employeecontract')),
                ('id_responsible_user', models.ForeignKey(db_column='id_responsible_user', on_delete=django.db.models.deletion.PROTECT, related_name='payrolls_responsible', to='users.user')),
            ],
            options={
                'db_table': 'payrolls',
            },
        ),
        migrations.CreateModel(
            name='PayrollDeduction',
            fields=[
                ('id_payroll_deduction', models.AutoField(db_column='id_payroll_deduction', primary_key=True, serialize=False)),
                ('amount_type', models.CharField(choices=[('Porcentaje', 'Porcentaje'), ('fijo', 'Fijo')], db_column='amount_type', max_length=20)),
                ('amount_value', models.FloatField(db_column='amount_value')),
                ('application_deduction_type', models.CharField(choices=[('SalarioBase', 'Salario Base'), ('SalarioFinal', 'Salario Final'), ('SalarioPorHora', 'Salario Por Hora')], db_column='application_deduction_type', max_length=20)),
                ('start_date_deduction', models.DateField(blank=True, db_column='start_date_deduction', null=True)),
                ('end_date_deductions', models.DateField(blank=True, db_column='end_date_deductions', null=True)),
                ('description', models.CharField(blank=True, db_column='description', max_length=255, null=True)),
                ('amount', models.FloatField(blank=True, db_column='amount', null=True)),
                ('deduction_type', models.ForeignKey(db_column='deduction_type', on_delete=django.db.models.deletion.PROTECT, related_name='payroll_deductions_by_type', to='parameterization.types')),
                ('payroll', models.ForeignKey(db_column='id_payroll', on_delete=django.db.models.deletion.PROTECT, related_name='payroll_deductions', to='payroll.payroll')),
            ],
            options={
                'db_table': 'payroll_deductions',
            },
        ),
        migrations.CreateModel(
            name='PayrollIncrease',
            fields=[
                ('id_payroll_increase', models.AutoField(db_column='id_payroll_increase', primary_key=True, serialize=False)),
                ('amount_type', models.CharField(choices=[('Porcentaje', 'Porcentaje'), ('fijo', 'Fijo')], db_column='amount_type', max_length=20)),
                ('amount_value', models.FloatField(db_column='amount_value')),
                ('application_increase_type', models.CharField(choices=[('SalarioBase', 'Salario Base'), ('SalarioFinal', 'Salario Final'), ('SalarioPorHora', 'Salario Por Hora')], db_column='application_increase_type', max_length=20)),
                ('start_date_increase', models.DateField(blank=True, db_column='start_date_increase', null=True)),
                ('end_date_increase', models.DateField(blank=True, db_column='end_date_increase', null=True)),
                ('description', models.CharField(blank=True, db_column='description', max_length=255, null=True)),
                ('amount', models.FloatField(blank=True, db_column='amount', null=True)),
                ('increase_type', models.ForeignKey(db_column='increase_type', on_delete=django.db.models.deletion.PROTECT, related_name='payroll_increases_by_type', to='parameterization.types')),
                ('payroll', models.ForeignKey(db_column='id_payroll', on_delete=django.db.models.deletion.PROTECT, related_name='payroll_increases', to='payroll.payroll')),
            ],
            options={
                'db_table': 'payroll_increases',
            },
        ),
    ]
