# Generated by Django 5.2.4 on 2025-11-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_alter_employee_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeenews',
            name='news_type',
            field=models.CharField(choices=[('CREACION_EMPLEADO', 'Creación de empleado'), ('ACTUALIZACION_EMPLEADO', 'Actualizar empleado'), ('DESACTIVACION_EMPLEADO', 'Desactivar empleado'), ('ACTIVACION_EMPLEADO', 'Activar empleado'), ('GENERAR_OTRO_SI', 'Generar otro si'), ('CAMBIO_CONTRATO', 'Cambio de contrato'), ('FINALIZACION_CONTRATO', 'Finalización de contrato')], max_length=30),
        ),
    ]
