# Generated by Django 5.2.4 on 2025-11-20 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0012_alter_employeecontractdeduction_application_deduction_type_and_more'),
        ('payroll', '0012_alter_employeenews_news_type'),
    ]

    operations = [
    ]
