# Generated by Django 5.2.4 on 2025-11-22 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameterization', '0014_employeecharge_contract_prefix'),
        ('payroll', '0014_alter_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecontract',
            name='contract_termination_reason',
            field=models.ForeignKey(blank=True, db_column='contract_termination_reason', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_contracts_by_termination_reason', to='parameterization.types'),
        ),
    ]
