# Generated by Django 5.2.4 on 2025-11-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0015_employeecontract_contract_termination_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishedcontract',
            name='days_of_week',
            field=models.ManyToManyField(blank=True, db_table='established_contract_days_of_week', related_name='contracts', to='payroll.daysofweek'),
        ),
    ]
