# Generated by Django 5.2.4 on 2025-11-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0015_employeecontract_contract_termination_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='base_salary',
            field=models.FloatField(db_column='base_salary', default=0.0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='net_pay',
            field=models.FloatField(db_column='net_pay', default=0.0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='time_worked',
            field=models.FloatField(db_column='time_worked', default=0.0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='total_deductions',
            field=models.FloatField(db_column='total_deductions', default=0.0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='total_increments',
            field=models.FloatField(db_column='total_increments', default=0.0),
        ),
    ]
