# Generated by Django 5.2.4 on 2025-11-23 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0016_establishedcontract_days_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecontract',
            name='days_of_week',
            field=models.ManyToManyField(blank=True, db_table='employee_contract_days_of_week', related_name='employee_contracts', to='payroll.daysofweek'),
        ),
    ]
