# Generated by Django 5.2.4 on 2025-11-23 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0016_payroll_base_salary_payroll_net_pay_and_more'),
        ('payroll', '0017_employeecontract_days_of_week'),
    ]

    operations = [
    ]
