# Generated by Django 5.2.4 on 2025-11-23 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0018_merge_20251122_1932'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecontractdeduction',
            name='application_deduction_type',
            field=models.CharField(choices=[('SalarioBase', 'Salario Base'), ('SalarioFinal', 'Salario Final')], db_column='application_deduction_type', max_length=20),
        ),
        migrations.AlterField(
            model_name='establisheddeduction',
            name='application_deduction_type',
            field=models.CharField(choices=[('SalarioBase', 'Salario Base'), ('SalarioFinal', 'Salario Final')], db_column='application_deduction_type', max_length=20),
        ),
        migrations.AlterField(
            model_name='payrolldeduction',
            name='application_deduction_type',
            field=models.CharField(choices=[('SalarioBase', 'Salario Base'), ('SalarioFinal', 'Salario Final')], db_column='application_deduction_type', max_length=20),
        ),
        migrations.CreateModel(
            name='TemporaryPayrollAdjustment',
            fields=[
                ('id_temp_adjustment', models.AutoField(primary_key=True, serialize=False)),
                ('adjustment_name', models.CharField(max_length=255)),
                ('adjustment_type', models.CharField(choices=[('deduccion', 'Deducción'), ('incremento', 'Incremento')], max_length=20)),
                ('amount_type', models.CharField(choices=[('Porcentaje', 'Porcentaje'), ('fijo', 'Fijo')], max_length=20)),
                ('amount_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('application_type', models.CharField(choices=[('SalarioBase', 'Salario Base'), ('SalarioFinal', 'Salario Final')], db_column='application_deduction_type', max_length=20)),
                ('start_date_adjustment', models.DateField()),
                ('end_date_adjustment', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('rejected', 'Rechazado')], default='pending', max_length=20)),
                ('batch_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_payroll_adjustments', to='payroll.employee')),
                ('user_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_temp_adjustments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'temporary_payroll_adjustments',
            },
        ),
    ]
