# Generated by Django 5.2.4 on 2025-11-23 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0019_alter_employeecontractdeduction_application_deduction_type_and_more'),
        ('users', '0002_alter_user_id_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporarypayrolladjustment',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='temporarypayrolladjustment',
            name='user_creator',
        ),
        migrations.AddField(
            model_name='temporarypayrolladjustment',
            name='id_employee',
            field=models.ForeignKey(db_column='id_employee', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='temporary_payroll_adjustments_id_employee', to='payroll.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temporarypayrolladjustment',
            name='id_responsible_user',
            field=models.ForeignKey(db_column='id_responsible_user', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='temporary_payroll_adjustments_id_responsible_user', to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='temporarypayrolladjustment',
            name='status',
            field=models.CharField(choices=[('pending', 'Aceptado'), ('confirmed', 'Confirmado'), ('rejected', 'Rechazado')], default='pending', max_length=20),
        ),
    ]
