# Generated by Django 5.2.4 on 2025-11-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0020_remove_temporarypayrolladjustment_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarypayrolladjustment',
            name='end_date_adjustment',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='temporarypayrolladjustment',
            name='start_date_adjustment',
            field=models.DateField(null=True),
        ),
    ]
