# Generated by Django 5.2.4 on 2025-11-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0021_alter_temporarypayrolladjustment_end_date_adjustment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecontract',
            name='working_hours',
            field=models.FloatField(blank=True, db_column='working_hours', null=True),
        ),
        migrations.AddField(
            model_name='establishedcontract',
            name='working_hours',
            field=models.FloatField(blank=True, db_column='working_hours', null=True),
        ),
    ]
