# Generated by Django 5.2.4 on 2025-11-25 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0022_employeecontract_working_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrolldeduction',
            name='calculated_amount',
            field=models.FloatField(blank=True, db_column='calculated_amount', null=True),
        ),
        migrations.AddField(
            model_name='payrollincrease',
            name='calculated_amount',
            field=models.FloatField(blank=True, db_column='calculated_amount', null=True),
        ),
    ]
