# Generated by Django 5.2.4 on 2025-11-25 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameterization', '0014_employeecharge_contract_prefix'),
        ('payroll', '0024_alter_employeenews_news_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='currency_type',
            field=models.ForeignKey(db_column='currency_type', on_delete=django.db.models.deletion.PROTECT, related_name='pyroll_by_currency_type', to='parameterization.units'),
            preserve_default=False,
        ),
    ]
