# Generated by Django 5.2.4 on 2026-04-20 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameterization', '0014_employeecharge_contract_prefix'),
        ('payroll', '0025_payroll_currency_type'),
        ('service_requests', '0026_auto_20251113_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='date_payment',
            field=models.DateField(blank=True, db_column='date_payment', null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='payment_method',
            field=models.ForeignKey(blank=True, help_text='Método de pago (ref: PaymentMethod)', null=True, on_delete=django.db.models.deletion.PROTECT, to='service_requests.paymentmethod'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='status',
            field=models.ForeignKey(default=16, help_text='Estado actual de la factura (ref: Statues)', on_delete=django.db.models.deletion.PROTECT, to='parameterization.statues'),
        ),
    ]
