# Generated by Django 5.2.4 on 2025-09-22 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parameterization', '0013_remove_units_description_units_id_types_units_symbol_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id_maintenance', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('registration_date', models.DateTimeField(auto_now_add=True, db_column='registration_date')),
                ('modification_date', models.DateTimeField(auto_now=True, db_column='modification_date')),
                ('id_responsible_user', models.ForeignKey(db_column='id_responsible_user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances_responsible', to=settings.AUTH_USER_MODEL)),
                ('maintenance_status', models.ForeignKey(db_column='maintenance_status', on_delete=django.db.models.deletion.PROTECT, related_name='maintenances_by_status', to='parameterization.types')),
                ('maintenance_type', models.ForeignKey(db_column='maintenance_type', on_delete=django.db.models.deletion.PROTECT, related_name='maintenances_by_type', to='parameterization.types')),
            ],
            options={
                'db_table': 'maintenance',
            },
        ),
    ]
