# Generated by Django 5.2.4 on 2025-09-23 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        ('parameterization', '0013_remove_units_description_units_id_types_units_symbol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='description',
            field=models.CharField(db_column='description', max_length=300),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_status',
            field=models.ForeignKey(db_column='maintenance_status', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='maintenances_by_status', to='parameterization.types'),
        ),
    ]
