# Generated by Django 5.2.4 on 2025-09-23 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_maintenance_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='name',
            field=models.CharField(db_column='name', max_length=100, unique=True),
        ),
    ]
