# Generated by Django 5.2.4 on 2025-09-23 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_alter_maintenance_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='id_responsible_user',
            field=models.ForeignKey(db_column='id_responsible_user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenances_responsible', to=settings.AUTH_USER_MODEL),
        ),
    ]
