# Generated by Django 5.2.4 on 2025-09-23 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_alter_maintenance_maintenance_status'),
        ('parameterization', '0013_remove_units_description_units_id_types_units_symbol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_status',
            field=models.ForeignKey(db_column='maintenance_status', on_delete=django.db.models.deletion.PROTECT, related_name='maintenances_by_status', to='parameterization.statues'),
        ),
    ]
