# Generated by Django 5.2.4 on 2025-09-23 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_alter_maintenance_maintenance_status'),
        ('users', '0002_alter_user_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='id_responsible_user',
            field=models.ForeignKey(db_column='id_responsible_user', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='maintenances_responsible', to='users.user'),
            preserve_default=False,
        ),
    ]
