# Generated by Django 5.2.4 on 2025-09-27 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0008_alter_specifictechnicalsheet_operating_weight'),
        ('maintenance', '0007_alter_maintenance_id_responsible_user'),
        ('parameterization', '0013_remove_units_description_units_id_types_units_symbol_and_more'),
        ('users', '0002_alter_user_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceSchedulingConsecutive',
            fields=[
                ('id_maintenance_scheduling_consecutive', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField()),
                ('code', models.IntegerField(db_column='code', unique=True)),
            ],
            options={
                'db_table': 'maintenance_scheduling_consecutive',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id_maintenance_request', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='problem_description', max_length=300)),
                ('detected_at', models.DateField(db_column='detected_at')),
                ('registration_date', models.DateTimeField(auto_now=True, db_column='registration_date')),
                ('modification_date', models.DateTimeField(auto_now=True, db_column='modification_date')),
                ('id_machinery', models.ForeignKey(db_column='id_machinery', on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_requests', to='machinery.machinery')),
                ('id_responsible_user', models.ForeignKey(db_column='id_responsible_user', on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_requests_responsible', to='users.user')),
                ('maintenance_type', models.ForeignKey(db_column='maintenance_type', on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_requests_by_type', to='parameterization.types')),
                ('priority', models.ForeignKey(db_column='priority_type', on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_requests_by_priority', to='parameterization.types')),
                ('request_status', models.ForeignKey(db_column='request_status', on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_requests_by_status', to='parameterization.statues')),
            ],
            options={
                'db_table': 'maintenance_request',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceScheduling',
            fields=[
                ('id_maintenance_scheduling', models.AutoField(primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField(db_column='scheduled_at')),
                ('details', models.CharField(db_column='details', max_length=350)),
                ('registration_date', models.DateTimeField(auto_now=True, db_column='registration_date')),
                ('modification_date', models.DateTimeField(auto_now=True, db_column='modification_date')),
                ('assigned_technician', models.ForeignKey(db_column='id_assigned_technician', on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_schedulings_assigned', to='users.user')),
                ('id_machinery', models.ForeignKey(db_column='id_machinery', on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_schedulings', to='machinery.machinery')),
                ('id_maintenance_request', models.ForeignKey(blank=True, db_column='id_maintenance_request', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_schedulings', to='maintenance.maintenancerequest')),
                ('id_responsible_user', models.ForeignKey(db_column='id_responsible_user', on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_schedulings_responsible', to='users.user')),
                ('maintenance_type', models.ForeignKey(db_column='maintenance_type', on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_schedulings_by_type', to='parameterization.types')),
                ('id_consecutive', models.ForeignKey(db_column='id_consecutive', on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_schedulings', to='maintenance.maintenanceschedulingconsecutive')),
            ],
            options={
                'db_table': 'maintenance_scheduling',
            },
        ),
    ]
