# Generated by Django 5.2.4 on 2025-09-28 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_maintenanceschedulingconsecutive_maintenancerequest_and_more'),
        ('parameterization', '0013_remove_units_description_units_id_types_units_symbol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='justification',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='maintenancescheduling',
            name='justification',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='maintenancescheduling',
            name='maintenance_scheduling_status',
            field=models.ForeignKey(db_column='maintenance_scheduling_status', default=13, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_scheduling_by_status', to='parameterization.statues'),
            preserve_default=False,
        ),
    ]
