# Generated by Django 5.2.4 on 2025-09-29 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0009_maintenancerequest_justification_and_more'),
        ('users', '0002_alter_user_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='id_responsible_user',
            field=models.ForeignKey(db_column='id_responsible_user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_requests_responsible', to='users.user'),
        ),
    ]
