# Generated by Django 5.2.4 on 2025-09-29 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0010_alter_maintenancerequest_id_responsible_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancescheduling',
            name='id_consecutive',
        ),
        migrations.DeleteModel(
            name='MaintenanceSchedulingConsecutive',
        ),
    ]
