# Generated by Django 5.2.4 on 2025-09-30 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0011_remove_maintenancescheduling_id_consecutive_and_more'),
        ('parameterization', '0013_remove_units_description_units_id_types_units_symbol_and_more'),
        ('users', '0002_alter_user_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceReport',
            fields=[
                ('id_maintenance_report', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=255)),
                ('description', models.CharField(db_column='description', max_length=600)),
                ('creation_date', models.DateField(auto_now_add=True, db_column='creation_date')),
                ('spare_parts_total_cost', models.FloatField(db_column='spare_parts_total_cost', default=0.0)),
                ('time_invested_hours', models.IntegerField(db_column='time_invested_hours')),
                ('time_invested_minutes', models.IntegerField(db_column='time_invested_minutes')),
                ('recommendations', models.TextField(blank=True, db_column='recommendations', null=True)),
                ('total_cost', models.FloatField(db_column='total_cost', default=0.0)),
                ('registration_date', models.DateTimeField(auto_now=True, db_column='registration_date')),
                ('modification_date', models.DateTimeField(auto_now=True, db_column='modification_date')),
                ('id_maintenance_scheduling', models.ForeignKey(db_column='id_maintenance_scheduling', on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_reports', to='maintenance.maintenancescheduling')),
                ('id_responsible_user', models.ForeignKey(db_column='id_responsible_user', on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_reports_responsible', to='users.user')),
            ],
            options={
                'db_table': 'maintenance_reports',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSpareParts',
            fields=[
                ('id_maintenance_spare_parts', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('spare_parts_cost', models.FloatField(db_column='spare_parts_cost')),
                ('registration_date', models.DateTimeField(auto_now=True, db_column='registration_date')),
                ('modification_date', models.DateTimeField(auto_now=True, db_column='modification_date')),
                ('spare_part_brand', models.ForeignKey(db_column='spare_part_brand', on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_spare_parts_by_brand', to='parameterization.brands')),
            ],
            options={
                'db_table': 'maintenance_spare_parts',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceMaintenanceReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now=True, db_column='registration_date')),
                ('modification_date', models.DateTimeField(auto_now=True, db_column='modification_date')),
                ('id_maintenance', models.ForeignKey(db_column='id_maintenance', on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_reports_relations', to='maintenance.maintenance')),
                ('id_maintenance_report', models.ForeignKey(db_column='id_maintenance_report', on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_relations', to='maintenance.maintenancereport')),
            ],
            options={
                'db_table': 'maintenance_maintenance_reports',
                'unique_together': {('id_maintenance', 'id_maintenance_report')},
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSparePartsMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.IntegerField(db_column='quantity_used', default=1)),
                ('cost_at_time', models.FloatField(db_column='cost_at_time')),
                ('registration_date', models.DateTimeField(auto_now=True, db_column='registration_date')),
                ('modification_date', models.DateTimeField(auto_now=True, db_column='modification_date')),
                ('id_maintenance_report', models.ForeignKey(db_column='id_maintenance_report', on_delete=django.db.models.deletion.CASCADE, related_name='spare_parts_relations', to='maintenance.maintenancereport')),
                ('id_maintenance_spare_part', models.ForeignKey(db_column='id_maintenance_spare_part', on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_relations', to='maintenance.maintenancespareparts')),
            ],
            options={
                'db_table': 'maintenance_spare_parts_maintenance',
                'unique_together': {('id_maintenance_spare_part', 'id_maintenance_report')},
            },
        ),
    ]
