# Generated by Django 5.2.4 on 2025-09-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0012_maintenancereport_maintenancespareparts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancemaintenancereports',
            name='maintenance_cost',
            field=models.FloatField(db_column='maintenance_cost', default=0.0),
        ),
    ]
