# Generated by Django 5.2.4 on 2025-10-01 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0013_maintenancemaintenancereports_maintenance_cost'),
        ('users', '0002_alter_user_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='id_response_user',
            field=models.ForeignKey(db_column='id_response_user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_requests_response_user', to='users.user'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='response_date',
            field=models.DateTimeField(db_column='response_date', null=True),
        ),
    ]
