# Generated by Django 5.2.4 on 2025-10-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0014_maintenancerequest_id_response_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='id_maintenance_request',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
