# Generated by Django 5.2.4 on 2025-10-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0015_alter_maintenancerequest_id_maintenance_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancescheduling',
            name='id_maintenance_scheduling',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
