# Generated by Django 5.2.4 on 2025-10-02 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0014_auto_20251002_0103'),
        ('maintenance', '0016_alter_maintenancescheduling_id_maintenance_scheduling'),
    ]

    operations = [
    ]
