# Generated by Django 5.2.4 on 2025-10-02 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0017_merge_20251002_0045'),
        ('parameterization', '0013_remove_units_description_units_id_types_units_symbol_and_more'),
        ('users', '0002_alter_user_id_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancereportspareparts',
            name='spare_parts_cost',
        ),
        migrations.AddField(
            model_name='maintenancemaintenancereports',
            name='id_technician',
            field=models.ForeignKey(db_column='id_technician', default=1, help_text='Técnico que realizó el mantenimiento', on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_tasks_performed', to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='currency_unit',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.PROTECT, related_name='currency_unit', to='parameterization.units'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MaintenanceReportUser',
            fields=[
                ('id_maintenance_report_user', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_date', models.DateTimeField(auto_now_add=True, db_column='assignment_date')),
                ('id_maintenance_report', models.ForeignKey(db_column='id_maintenance_report', on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_report_users', to='maintenance.maintenancereport')),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_report_users', to='users.user')),
            ],
            options={
                'db_table': 'maintenance_report_users',
                'unique_together': {('id_maintenance_report', 'id_user')},
            },
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='assigned_users',
            field=models.ManyToManyField(help_text='Usuarios asignados a este reporte de mantenimiento', related_name='assigned_maintenance_reports', through='maintenance.MaintenanceReportUser', through_fields=('id_maintenance_report', 'id_user'), to='users.user'),
        ),
    ]
