# Generated by Django 5.2.4 on 2025-10-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0018_remove_maintenancereportspareparts_spare_parts_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancereport',
            name='time_invested_seconds',
            field=models.IntegerField(db_column='time_invested_seconds', default=0),
            preserve_default=False,
        ),
    ]
