# Generated by Django 5.2.4 on 2025-10-04 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0019_maintenancereport_time_invested_seconds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancereport',
            name='creation_date',
        ),
    ]
