# Generated by Django 5.2.4 on 2025-11-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0020_remove_maintenancereport_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='description',
            field=models.CharField(db_column='problem_description', max_length=1000),
        ),
    ]
