# Generated by Django 5.2.4 on 2025-10-29 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machinery', '0021_alter_eventtypemachinery_alert_enabled_and_more'),
        ('service_requests', '0024_merge_20251029_0414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id_data', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.FloatField()),
                ('registered_at', models.DateTimeField()),
                ('id_device', models.ForeignKey(db_column='id_device', on_delete=django.db.models.deletion.PROTECT, to='machinery.telemetrydevices')),
                ('id_parameter', models.ForeignKey(db_column='id_parameter', on_delete=django.db.models.deletion.PROTECT, to='machinery.parameters')),
                ('id_request', models.ForeignKey(db_column='id_request', on_delete=django.db.models.deletion.PROTECT, to='service_requests.servicerequest')),
            ],
            options={
                'db_table': 'data',
            },
        ),
    ]
