# Generated by Django 5.2.4 on 2025-10-31 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='alert',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='obd_fault',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='data',
            field=models.FloatField(null=True),
        ),
    ]
