# Generated by Django 5.2.4 on 2025-11-02 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0021_alter_eventtypemachinery_alert_enabled_and_more'),
        ('monitoring', '0002_data_alert_data_obd_fault_alter_data_data'),
        ('service_requests', '0024_merge_20251029_0414'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTelemetry',
            fields=[
                ('id_historical_telemetry', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('ignition_status', models.IntegerField(blank=True, null=True)),
                ('movement_status', models.IntegerField(blank=True, null=True)),
                ('speed', models.IntegerField(blank=True, null=True)),
                ('gps_location', models.CharField(blank=True, max_length=255, null=True)),
                ('gsm_signal', models.IntegerField(blank=True, null=True)),
                ('rpm', models.IntegerField(blank=True, null=True)),
                ('engine_temp', models.IntegerField(blank=True, null=True)),
                ('engine_load', models.IntegerField(blank=True, null=True)),
                ('oil_level', models.IntegerField(blank=True, null=True)),
                ('fuel_level', models.IntegerField(blank=True, null=True)),
                ('fuel_used_gps', models.FloatField(blank=True, null=True)),
                ('instant_consumption', models.FloatField(blank=True, null=True)),
                ('odometer_total', models.BigIntegerField(blank=True, null=True)),
                ('odometer_trip', models.IntegerField(blank=True, null=True)),
                ('event_type', models.IntegerField(blank=True, null=True)),
                ('event_g_value', models.IntegerField(blank=True, null=True)),
                ('logistic_status', models.CharField(blank=True, help_text='Ida, Vuelta, Trabajo', max_length=20, null=True)),
                ('alert', models.BooleanField(default=False)),
                ('alert_reason', models.TextField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('id_device', models.ForeignKey(db_column='id_device', on_delete=django.db.models.deletion.PROTECT, related_name='historical_telemetry', to='machinery.telemetrydevices')),
                ('id_machinery', models.ForeignKey(db_column='id_machinery', on_delete=django.db.models.deletion.PROTECT, related_name='historical_telemetry', to='machinery.machinery')),
                ('id_request', models.ForeignKey(blank=True, db_column='id_request', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historical_telemetry', to='service_requests.servicerequest')),
            ],
            options={
                'db_table': 'monitoring_historicaltelemetry',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'id_machinery'], name='monitoring__timesta_cad69f_idx'), models.Index(fields=['id_machinery', 'id_request'], name='monitoring__id_mach_adcb07_idx')],
            },
        ),
    ]
