# Generated by Django 5.2.4 on 2025-11-06 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0021_alter_eventtypemachinery_alert_enabled_and_more'),
        ('monitoring', '0002_data_alert_data_obd_fault_alter_data_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='id_machinery',
            field=models.ForeignKey(db_column='id_machinery', default=1, on_delete=django.db.models.deletion.PROTECT, to='machinery.machinery'),
            preserve_default=False,
        ),
    ]
