# Generated by Django 5.2.4 on 2025-11-06 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_data_id_machinery'),
        ('users', '0002_alter_user_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='id_user',
            field=models.ForeignKey(db_column='id_user', default=1, on_delete=django.db.models.deletion.PROTECT, to='users.user'),
            preserve_default=False,
        ),
    ]
