# Generated by Django 5.2.4 on 2025-11-02 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_historicaltelemetry'),
        ('service_requests', '0024_merge_20251029_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltelemetry',
            name='id_request',
            field=models.ForeignKey(db_column='id_request', on_delete=django.db.models.deletion.PROTECT, related_name='historical_telemetry', to='service_requests.servicerequest'),
        ),
    ]
